version: '3.0'
services:
  local-postgres:
    image: postgres:11-alpine
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: testadmin
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: postgres
    volumes:
      - '~/env/docker/postgres/volumes/local-postgres:/var/lib/postgresql/data'
      - './dump:/docker-entrypoint-initdb.d'