spring:
  profiles:
    active: test-postgresql
---
spring:
  config:
    activate:
      on-profile: test-postgresql
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
    username: postgres
    password: 1111
#    initialization-mode: always
  #    schema: classpath*:database/testdocker/schema.sql
#    data: classpath*:database/testdocker/data.sql
#    hikari:
#      schema: classpath*:database/testdocker/schema.sql
  data:
    jpa:
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
  jpa:
    hibernate:
      ddl-auto: none